services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    command: npm run dev -- --host
    ports:
      - "5173:5173"

  playwright-test:
    image: todos-pw-test
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npx playwright test cartPage.spec.ts --project=chromium
    volumes:
      - ./playwright-report/:/app/playwright-report
      - ./test-results/:/app/test-results